
services:
  - type: web
    name: movie-detector
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: TMDB_API_KEY
        sync: false
      - key: GOOGLE_CREDENTIALS_JSON
        sync: false
